import "../style/globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Provider from "@/components/Provider"
import NavMenu from "@/components/NavMenu"
import { getServerSession } from "next-auth"
import { authOptions } from "./api/auth/[...nextauth]/route"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <main className="min-h-screen">
            <NavMenu />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
